# Site settings

# General settings
lang: en
title: Bogović corner
email: bogovic@protonmail.com
author: Ivan Bogović
description: "Bogović small corner with various topics"
keywords: "network, security, consultant"

# URL settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ibogovic-hub.github.io" # the base hostname & protocol for your site
home-repo: "https://ibogovic-hub.github.io"

# Social services
twitter_username: iBogovic
github_username:  ibogovic-hub
fb_username: ivbogovic
# vk_username:
# gplus_username:
# skype_username:
# bitbucket_username: orlovmax
linkedin_username: bogovic-consultant

# Multilanguage blog settings: names, base url and current lang
# langs:
#   "en": "http://blog.orlovmax.com"
#   "ru": "http://rublog.orlovmax.com"
#   "ua": "http://uablog.orlovmax.com"
# lang_current: "ua"

# Default src
start_img: "static/images/bg/start.jpg"
end_img: "static/images/bg/end.jpg"
thumb_img: "img/pic.jpg"

disqus-code: "jekyll-inclusion"

#Custom search engine ID
# custom-search-engine_id: "007847994425388688875:2onbkc4tu2y"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 9
paginate_path: "page/:num/"
exclude: []
incremental: true

source: build
destination: deploy

# Category pages settings
categories:
  # category pages url
  url: /category/
  # category pages slug, ex. page-1 or page2. Number by default
  slug: ''
  # category name word delimiter, '_' by defult
  delimiter: '_'
  layout: category.html

# Tag pages settings
tags:
  # tag pages url
  url: /tag/
  # tag pages slug, ex. page-1 or page2. Number by default
  slug: ''
  # tag name word delimiter, '_' by defult
  delimiter: '_'
  layout: tag.html
