## => Site Settings
##############################
text_skin: "dark" # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: "tomorrow-night-bright" # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : https://ibogovic-hub.github.io
baseurl : # does not include hostname
title   : bogovic small corner
logo: assets/images/logo/3a99in5a.png
favicon: assets/images/logo/facicon.ico
cover: assets/images/wall/wall.jpeg
description: > # this means to ignore newlines until "Language & timezone"
  working on this...


## => Language and Timezone
##############################
lang: # the language of your site, default as "en"
timezone: Europe/Zagreb


## => Author and Social
##############################
author:
  type      : # "person" (default), "organization"
  name      : bogovic
  url       : https://ibogovic-hub.github.io
  avatar    : /assets/images/logo/3a99in5a.svg
  bio       : on my way up.
  email     :
  facebook  : ivbogovic
  twitter   : iBogovic
  telegram  : ibogovic
  linkedin  : bogovic-consultant
  github    : ibogovic-hub


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: ibogovic-hub/ibogovic-hub.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : "/" # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: "h1,h2,h3,h4"


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true
mathjax_autoNumber: true

## Mermaid
mermaid: true

## Chart
chart: true


## => Paginate
##############################
paginate: 10
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: false # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /_data
  - /_includes
  - /_posts
  - /index.html

# defaults:
#   - scope:
#       path: "_posts"
#       type: posts
#     values:
#       layout: article
#       sharing: true
#       license: true
#       aside:
#         toc: true
#       show_edit_on_github: true
#       show_subscribe: false
#       pageview: true

defaults:
  ## home
  - scope:
      path: "/"
    values:
      articles:
        excerpt_type: html
  ## posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      category: post
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
      # lightbox: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

data_dir: /docs/_data